name: Build RTL8821AU Driver

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git dkms bc linux-headers-generic

    - name: Clone driver and patch USB ID
      run: |
        git clone https://github.com/aircrack-ng/rtl8812au.git -b v5.6.4.2
        cd rtl8812au
        sed -i '/{USB_DEVICE(0x2357, 0x011F)/a \ \t{USB_DEVICE(0x2357, 0x0120), .driver_info = RTL8821}, /* TP-Link T2U Plus */' os_dep/linux/usb_intf.c

    - name: Build driver
      run: |
        cd rtl8812au
        make -j$(nproc)

    - name: Upload built module
      uses: actions/upload-artifact@v3
      with:
        name: rtl8821au-ko
        path: rtl8812au/8821au.ko

