name: Build RTL8821AU Driver

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential dkms git linux-headers-$(uname -r)

    - name: Clone driver and patch USB ID
      run: |
        git clone https://github.com/aircrack-ng/rtl8812au.git -b v5.6.4.2
        cd rtl8812au
        sed -i '/{USB_DEVICE(0x2357, 0x011F)/a \ \t{USB_DEVICE(0x2357, 0x0120), .driver_info = RTL8821}, /* TP-Link T2U Plus */' os_dep/linux/usb_intf.c

    - name: Build driver
      run: |
        cd rtl8812au
        make -j$(nproc)

    - name: List generated kernel modules
      run: |
        echo "Searching for *.ko files in rtl8812au/"
        find rtl8812au -name '*.ko'

    - name: Upload built module(s)
      uses: actions/upload-artifact@v4
      with:
        name: rtl8821au-modules
        path: rtl8812au/**/*.ko

